let cfg={tools:[],applications:[],plans:[],site:{}};let currentTarget='single',utilityMode='',files={single:null,left:null,right:null};let settings={clothingEnabled:false,clothingType:'white shirt',fullClothing:true,backgroundEnabled:false,background:'original',size:'২×২ ইঞ্চি'};let adminToken=localStorage.getItem('soho_admin')||'';const $=id=>document.getElementById(id);
function toast(m){const t=$('toast');t.textContent=m;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2800)}
function openSheet(id){closeSheets();$('overlay').classList.add('open');$(id).classList.add('open')};function closeSheets(){document.querySelectorAll('.sheet').forEach(x=>x.classList.remove('open'));$('overlay').classList.remove('open')};function setView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));$(id).classList.add('active');closeSheets();window.scrollTo(0,0)}function goHome(){setView('homeView');renderHome()}function showProfile(){setView('profileView');updateCredit()}
function openEditor(mode='single'){setView('editorView');if(mode==='remove'){utilityMode='remove';$('prompt').value='ব্যাকগ্রাউন্ড পরিষ্কারভাবে সরিয়ে দিন এবং বিষয়টিকে স্বাভাবিক রাখুন।'}else utilityMode='ai'}
function toggleMode(){const d=$('dualUpload'),s=$('singleUpload');d.classList.toggle('hidden');s.classList.toggle('hidden');if(!d.classList.contains('hidden')){currentTarget='left';toast('জয়েন্ট মোড চালু হয়েছে')}}
function pickImage(t){currentTarget=t;$('fileInput').value='';$('fileInput').click()}
$('fileInput').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;if(f.size>60*1024*1024)return toast('ফাইলের আকার 60MB-এর বেশি হতে পারবে না');files[currentTarget]=f;const map={single:['singleUpload','singlePreview'],left:['leftBox','leftPreview'],right:['rightBox','rightPreview']};if(map[currentTarget]){const [box,pre]=map[currentTarget];$(pre).src=URL.createObjectURL(f);$(box).classList.add('has-image');$(box).querySelector('.remove-img')?.classList.remove('hidden')}if(currentTarget==='utility')runUtility(f);else toast('ছবি সফলভাবে আপলোড হয়েছে')});
function removeSlot(s){files[s]=null;const box=s==='left'?$('leftBox'):$('rightBox'),pre=s==='left'?$('leftPreview'):$('rightPreview');box.classList.remove('has-image');pre.removeAttribute('src');box.querySelector('.remove-img')?.classList.add('hidden')}
function openQuick(){openSheet('quickSheet')};function focusPrompt(){openSheet('settingsSheet');setTimeout(()=>$('prompt').focus(),250)};function scrollToTools(){setView('toolsView');renderAllTools()};function openSearch(){openSheet('searchSheet');setTimeout(()=>$('searchInput').focus(),200)}
const sizes=[['২×২ ইঞ্চি','যুক্তরাষ্ট্র (US), ভারত'],['৩৫×৪৫ মিমি','যুক্তরাজ্য (UK), ইউরোপ'],['৪০×৬০ মিমি','সৌদি আরব, কুয়েত'],['৪০×৫০ মিমি','হংকং, কাজাখস্তান'],['৪০×৪০ মিমি','আর্জেন্টিনা, মেক্সিকো'],['৫০×৫০ মিমি','বাহামাস, কোস্টারিকা'],['৫০×৭০ মিমি','কানাডা (PR/ভিসা)'],['৩৮×৪৮ মিমি','চীন'],['৩৫×৫০ মিমি','মালয়েশিয়া'],['৩৬×৪৭ মিমি','আলবেনিয়া'],['৩৮×৪৮ মিমি','কাতার'],['৫০×৬০ মিমি','তুরস্ক']];$('sizeGrid').innerHTML=sizes.map((s,i)=>`<button class="${i===0?'selected':''}" onclick="selectSize(this,'${s[0]}')"><b>${s[0]}</b><br><span>${s[1]}</span></button>`).join('');function selectSize(el,v){document.querySelectorAll('.size-grid button').forEach(x=>x.classList.remove('selected'));el.classList.add('selected');settings.size=v;toast('ছবির মাপ নির্বাচিত হয়েছে')}
function toggleClothing(){settings.clothingEnabled=!settings.clothingEnabled;$('clothingToggle').textContent=settings.clothingEnabled?'ON':'OFF';$('clothingToggle').classList.toggle('on',settings.clothingEnabled);$('clothingOptions').classList.toggle('hidden',!settings.clothingEnabled)}function toggleBackground(){settings.backgroundEnabled=!settings.backgroundEnabled;$('bgToggle').textContent=settings.backgroundEnabled?'ON':'OFF';$('bgToggle').classList.toggle('on',settings.backgroundEnabled);$('bgOptions').classList.toggle('hidden',!settings.backgroundEnabled)}
document.querySelectorAll('.clothes-grid button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.clothes-grid button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');settings.clothingType=b.dataset.cloth;toast('পোশাক নির্বাচন করা হয়েছে')});document.querySelectorAll('.colors button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.colors button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');settings.background=b.dataset.bg;toast('ব্যাকগ্রাউন্ড নির্বাচন করা হয়েছে')});
async function post(url,fd){const r=await fetch(url,{method:'POST',body:fd});const d=await r.json().catch(()=>({}));if(!r.ok||!d.ok)throw new Error(d.error||'অনুরোধ ব্যর্থ হয়েছে');return d}
async function generateCurrent(){closeSheets();if(files.left&&files.right){return generateJoint()}if(files.single)return generateAI();toast('প্রথমে ছবি আপলোড করুন')}
async function generateAI(){toast('AI ছবি তৈরি করছে…');const fd=new FormData();fd.append('image',files.single);fd.append('prompt',$('prompt').value);fd.append('quality',$('quality').value);try{const d=await post('/api/ai-edit',fd);showSingleResult(d.image,d.original)}catch(e){toast(e.message)}}
async function generateJoint(){toast('জয়েন্ট ছবি তৈরি হচ্ছে…');const fd=new FormData();fd.append('left',files.left);fd.append('right',files.right);fd.append('clothingEnabled',settings.clothingEnabled);fd.append('clothingType',settings.clothingType);fd.append('fullClothing',settings.fullClothing);fd.append('backgroundEnabled',settings.backgroundEnabled);fd.append('background',settings.background);fd.append('photoSize',settings.size);fd.append('prompt',$('prompt').value);try{const d=await post('/api/joint-image',fd);$('resultImage').src=d.generated;$('downloadBtn').href=d.generated;$('origLeftResult').src=d.originalLeft;$('origRightResult').src=d.originalRight;$('resultPanel').classList.remove('hidden');$('dualUpload').classList.add('hidden');toast('জয়েন্ট ছবি সফলভাবে তৈরি হয়েছে')}catch(e){toast(e.message)}}
function showSingleResult(src,orig){$('resultImage').src=src;$('downloadBtn').href=src;$('origLeftResult').src=orig;$('origRightResult').removeAttribute('src');$('resultPanel').classList.remove('hidden');$('singleUpload').classList.add('hidden');showResultTab('generated');toast('ফলাফল প্রস্তুত')}
function showResultTab(t){document.querySelectorAll('.result-tabs button').forEach((b,i)=>b.classList.toggle('selected',(t==='generated'&&i===0)||(t==='original'&&i===1)));$('generatedWrap').classList.toggle('hidden',t!=='generated');$('originalWrap').classList.toggle('hidden',t!=='original')}
function regenerate(){$('resultPanel').classList.add('hidden');if(files.left&&files.right)$('dualUpload').classList.remove('hidden');else $('singleUpload').classList.remove('hidden');toast('সেটিং বদলে আবার তৈরি করুন')}
async function runUtility(file){if(utilityMode==='remove'){try{const fd=new FormData();fd.append('image',file);const d=await post('/api/remove-bg',fd);openEditor();showSingleResult(d.image,URL.createObjectURL(file))}catch(e){toast(e.message)}}else if(utilityMode==='ocr'){try{const fd=new FormData();fd.append('image',file);const d=await post('/api/ocr',fd);openSheet('utilitySheet');$('utilityTitle').textContent='ছবি থেকে লেখা';$('utilityText').textContent='OCR ফলাফল';$('ocrOutput').textContent=d.text||'কোনো লেখা পাওয়া যায়নি';$('ocrOutput').classList.remove('hidden')}catch(e){toast(e.message)}}else if(utilityMode==='compress'){const url=URL.createObjectURL(file);openSheet('utilitySheet');$('utilityTitle').textContent='ইমেজ কমপ্রেস';$('utilityText').innerHTML=`<img class="utility-preview" src="${url}"><br>ক্লায়েন্ট-সাইডে JPEG 70% হিসেবে ডাউনলোড করা যাবে।`;$('ocrOutput').classList.add('hidden');const a=document.createElement('a');a.className='primary wide';a.textContent='কমপ্রেসড ছবি ডাউনলোড';a.href=url;a.download='compressed.jpg';$('utilitySheet').appendChild(a)}}
function openUpload(mode){utilityMode=mode;openSheet('utilitySheet');$('utilityTitle').textContent=mode==='ocr'?'ছবি থেকে লেখা':mode==='remove'?'ব্যাকগ্রাউন্ড রিমুভ':'ইমেজ কমপ্রেস';$('utilityText').textContent='একটি ছবি আপলোড করুন';$('ocrOutput').classList.add('hidden')}
async function loadConfig(){try{cfg=await fetch('/api/config').then(r=>r.json());renderHome();renderJobs();renderAllTools();updateCredit()}catch(e){toast('কনফিগ লোড করা যায়নি')}}
function renderHome(){const enabled=cfg.tools?.filter(t=>t.enabled)||[];const defs={ai:['✦','এআই ফটো এডিট','ai'],joint:['👥','জয়েন্ট ছবি','joint'],remove:['▧','ব্যাকগ্রাউন্ড রিমুভ','bg'],compress:['▱','ইমেজ কমপ্রেস','manual'],ocr:['TXT','ছবি থেকে লেখা','tools'],docs:['▤','ডকুমেন্ট তৈরি','docs'],jobs:['JOB','চাকরির বিজ্ঞপ্তি','job']};$('mainTools').innerHTML=enabled.slice(0,6).map(t=>{const d=defs[t.id]||['✦',t.name,'tools'];const action=t.id==='joint'?"openEditor();toggleMode()":t.id==='ai'?"openEditor()":t.id==='remove'?"openUpload('remove')":t.id==='ocr'?"openUpload('ocr')":t.id==='compress'?"openUpload('compress')":t.id==='docs'?"setView('docsView')":"setView('jobsView');renderJobs()";return `<button class="tool-card ${d[2]}" onclick="${action}"><span class="tool-icon">${d[0]}</span><strong>${d[1]}</strong></button>`}).join('');$('miniTools').innerHTML=enabled.slice(0,8).map(t=>`<button onclick="${t.id==='ocr'?"openUpload('ocr')":t.id==='remove'?"openUpload('remove')":t.id==='compress'?"openUpload('compress')":"toast('এই টুলটি অ্যাডমিন থেকে কনফিগার করা যাবে')"}"><i>${t.id==='ocr'?'TXT':t.id==='remove'?'✂':t.id==='compress'?'▱':'✦'}</i><b>${t.name}</b>${t.badge?`<small>${t.badge}</small>`:''}</button>`).join('');$('creditBadge').textContent=localStorage.getItem('soho_credit')||'10'}
function renderAllTools(){$('allTools').innerHTML=(cfg.tools||[]).map(t=>`<button onclick="${t.id==='ai'?"openEditor()":t.id==='joint'?"openEditor();toggleMode()":t.id==='ocr'?"openUpload('ocr')":t.id==='remove'?"openUpload('remove')":t.id==='compress'?"openUpload('compress')":"toast('টুল প্রস্তুত')"}"><span>✦</span><div><b>${t.name}</b><small>${t.free?'ফ্রি':t.creditCost+' ক্রেডিট'} · ${t.limitType==='unlimited'?'আনলিমিটেড':t.limit+' ব্যবহার'}</small></div><em>${t.enabled?'ON':'OFF'}</em></button>`).join('')}
function renderJobs(){const a=(cfg.applications||[]).filter(x=>x.enabled);$('jobList').innerHTML=a.length?a.map(x=>`<article class="job-card"><span>💼</span><div><h3>${x.title}</h3><p>${x.description||'আবেদনের বিস্তারিত দেখুন'}</p><small>শেষ সময়: ${x.deadline||'উল্লেখ নেই'}</small></div><a href="${x.url||'#'}" target="_blank">আবেদন করুন ↗</a></article>`).join(''):`<div class="empty">এখনও কোনো আবেদন/চাকরির লিংক যোগ করা হয়নি। Admin Panel থেকে যোগ করুন।</div>`}
function openCredit(){openSheet('creditSheet');updateCredit()};function updateCredit(){const c=Number(localStorage.getItem('soho_credit')||10);$('creditBig').textContent=c;$('profileCredit').textContent=c;$('creditBadge').textContent=c;$('creditHistory').innerHTML='<div class="history-row"><span>ডেমো ব্যালেন্স</span><b>'+c+' ক্রেডিট</b></div>'}
function runSearch(){const q=$('searchInput').value.toLowerCase();const all=[...(cfg.tools||[]).map(x=>x.name),...(cfg.applications||[]).map(x=>x.title)];$('searchResults').innerHTML=all.filter(x=>x.toLowerCase().includes(q)).map(x=>`<div class="search-item">🔎 ${x}</div>`).join('')||'<div class="empty">কিছু পাওয়া যায়নি</div>'}
function openDoc(type){toast(type+' ডকুমেন্ট তৈরি মডিউল খুলছে');openSheet('settingsSheet');$('prompt').value=type+' তৈরি করার জন্য প্রয়োজনীয় তথ্য লিখুন।'}
function openAdmin(){setView('adminView');$('adminLogin').classList.toggle('hidden',!!adminToken);$('adminPanel').classList.toggle('hidden',!adminToken);if(adminToken)loadAdmin()}
async function adminLogin(){try{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('adminEmail').value,password:$('adminPassword').value})});const d=await r.json();if(!r.ok)throw new Error(d.error);adminToken=d.token;localStorage.setItem('soho_admin',adminToken);openAdmin();toast('Admin login সফল')}catch(e){toast(e.message)}}
function adminLogout(){adminToken='';localStorage.removeItem('soho_admin');openAdmin();toast('Logout হয়েছে')}
async function adminFetch(url,opts={}){opts.headers={...(opts.headers||{}),Authorization:'Bearer '+adminToken,'Content-Type':'application/json'};const r=await fetch(url,opts);const d=await r.json();if(!r.ok)throw new Error(d.error||'Admin request ব্যর্থ');return d}
async function loadAdmin(){try{const d=await adminFetch('/api/admin/state');cfg=d.state;renderAdminStats();adminTab('tools')}catch(e){adminLogout();toast(e.message)}}
function renderAdminStats(){const s=cfg;const credits=s.users.reduce((a,u)=>a+(u.credit||0),0);$('adminStats').innerHTML=`<div><b>${s.users.length}</b><span>ইউজার</span></div><div><b>${s.tools.filter(t=>t.enabled).length}</b><span>ON টুল</span></div><div><b>${credits}</b><span>ক্রেডিট</span></div><div><b>${s.applications.length}</b><span>আবেদন</span></div>`}
function adminTab(tab){document.querySelectorAll('.admin-tabs button').forEach(b=>b.classList.toggle('selected',b.textContent.includes(tab==='tools'?'টুল':tab==='users'?'ইউজার':tab==='plans'?'প্ল্যান':tab==='apps'?'আবেদন':'সেটিং')));if(tab==='tools')adminTools();if(tab==='users')adminUsers();if(tab==='plans')adminPlans();if(tab==='apps')adminApps();if(tab==='settings')adminSettings()}
function adminTools(){$('adminContent').innerHTML=`<div class="admin-section"><h3>টুল ON/OFF ও Credit/Limit</h3>${cfg.tools.map(t=>`<div class="admin-row"><div><b>${t.name}</b><small>${t.free?'ফ্রি':t.creditCost+' ক্রেডিট'} · ${t.limitType==='unlimited'?'আনলিমিটেড':t.limit+' ব্যবহার'}</small></div><div class="admin-controls"><button onclick="toggleTool('${t.id}',${!t.enabled})" class="${t.enabled?'on':''}">${t.enabled?'ON':'OFF'}</button><input type="number" value="${t.creditCost}" min="0" onchange="editTool('${t.id}',{creditCost:Number(this.value)})" title="Credit"><select onchange="editTool('${t.id}',{limitType:this.value})"><option value="unlimited" ${t.limitType==='unlimited'?'selected':''}>Unlimited</option><option value="daily" ${t.limitType==='daily'?'selected':''}>Daily</option><option value="monthly" ${t.limitType==='monthly'?'selected':''}>Monthly</option><option value="total" ${t.limitType==='total'?'selected':''}>Total</option></select></div></div>`).join('')}</div>`}
async function toggleTool(id,v){await editTool(id,{enabled:v})};async function editTool(id,data){try{await adminFetch('/api/admin/tools/'+id,{method:'PUT',body:JSON.stringify(data)});await loadAdmin();toast('টুল সেটিং আপডেট হয়েছে')}catch(e){toast(e.message)}}
function adminUsers(){$('adminContent').innerHTML=`<div class="admin-section"><h3>ইউজার ক্রেডিট ও Access</h3><form class="inline-form" onsubmit="addUser(event)"><input id="newUserName" placeholder="নাম"><input id="newUserCredit" type="number" placeholder="Credit"><input id="newUserDays" type="number" placeholder="দিন"><button class="primary">যোগ করুন</button></form>${cfg.users.map(u=>`<div class="admin-row"><div><b>${u.name}</b><small>${u.email||'ইমেইল নেই'} · ${u.accessDays||0} দিন</small></div><div class="admin-controls"><input type="number" value="${u.credit||0}" onchange="editUser('${u.id}',{credit:Number(this.value)})"><button onclick="editUser('${u.id}',{unlimited:${!u.unlimited}})">${u.unlimited?'UNLIMITED':'LIMIT'}</button></div></div>`).join('')}</div>`}
async function addUser(e){e.preventDefault();await adminFetch('/api/admin/users',{method:'POST',body:JSON.stringify({name:$('newUserName').value,credit:$('newUserCredit').value,accessDays:$('newUserDays').value})});await loadAdmin();toast('ইউজার যোগ হয়েছে')};async function editUser(id,data){await adminFetch('/api/admin/users/'+id,{method:'PUT',body:JSON.stringify(data)});await loadAdmin();toast('ইউজার আপডেট হয়েছে')}
function adminPlans(){$('adminContent').innerHTML=`<div class="admin-section"><h3>প্যাকেজ / প্ল্যান</h3><form class="inline-form" onsubmit="addPlan(event)"><input id="planName" placeholder="প্ল্যান নাম"><input id="planCredit" type="number" placeholder="Credit"><input id="planDays" type="number" placeholder="দিন"><label><input id="planUnlimited" type="checkbox"> Unlimited</label><button class="primary">যোগ করুন</button></form>${cfg.plans.map(p=>`<div class="admin-row"><div><b>${p.name}</b><small>${p.unlimited?'Unlimited':p.credit+' Credit'} · ${p.days} দিন</small></div><span class="status ${p.enabled?'good':'bad'}">${p.enabled?'ON':'OFF'}</span></div>`).join('')}</div>`}
async function addPlan(e){e.preventDefault();await adminFetch('/api/admin/plans',{method:'POST',body:JSON.stringify({name:$('planName').value,credit:$('planCredit').value,days:$('planDays').value,unlimited:$('planUnlimited').checked})});await loadAdmin();toast('প্ল্যান যোগ হয়েছে')}
function adminApps(){$('adminContent').innerHTML=`<div class="admin-section"><h3>আবেদন/চাকরির লিংক</h3><form class="inline-form" onsubmit="addApp(event)"><input id="appTitle" placeholder="শিরোনাম"><input id="appUrl" placeholder="https://..." type="url"><input id="appDeadline" placeholder="শেষ সময়"><input id="appDesc" placeholder="বর্ণনা"><button class="primary">যোগ করুন</button></form>${cfg.applications.map(a=>`<div class="admin-row"><div><b>${a.title}</b><small>${a.url} · ${a.deadline||''}</small></div><div class="admin-controls"><button onclick="editApp('${a.id}',{enabled:${!a.enabled}})">${a.enabled?'ON':'OFF'}</button><button class="danger" onclick="deleteApp('${a.id}')">মুছুন</button></div></div>`).join('')}</div>`}
async function addApp(e){e.preventDefault();await adminFetch('/api/admin/applications',{method:'POST',body:JSON.stringify({title:$('appTitle').value,url:$('appUrl').value,deadline:$('appDeadline').value,description:$('appDesc').value})});await loadAdmin();toast('আবেদন লিংক যোগ হয়েছে')};async function editApp(id,data){await adminFetch('/api/admin/applications/'+id,{method:'PUT',body:JSON.stringify(data)});await loadAdmin();toast('আবেদন আপডেট হয়েছে')};async function deleteApp(id){if(!confirm('এই আবেদনটি মুছবেন?'))return;await adminFetch('/api/admin/applications/'+id,{method:'DELETE'});await loadAdmin();toast('আবেদন মুছে গেছে')}
function adminSettings(){$('adminContent').innerHTML=`<div class="admin-section"><h3>সাইট সেটিংস</h3><label class="switch-row">Credit System <button class="switch ${cfg.settings.creditSystem?'on':''}" onclick="saveSettings({creditSystem:${!cfg.settings.creditSystem}})">${cfg.settings.creditSystem?'ON':'OFF'}</button></label><label>সাইটের নাম<input id="siteNameEdit" value="${cfg.settings.siteName||'সহজ কাজ'}"></label><button class="primary wide" onclick="saveSettings({siteName:$('siteNameEdit').value})">সেভ করুন</button></div>`};async function saveSettings(data){await adminFetch('/api/admin/settings',{method:'PUT',body:JSON.stringify(data)});await loadAdmin();toast('সেটিংস সেভ হয়েছে')}
function renderJobsOnLoad(){};
loadConfig();
